### ISSUE TITLE
Why does write_image ignore some SimpleITK errors?

### ISSUE THREAD

**Issue by gvtulder** [AIIMLab/fexp#2]
The following exception handling code in `write_image` makes some SimpleITK exceptions disappear. For example, if you try to save a Numpy array with an unsupported dtype, the exception from SimpleITK is caught by the first if statement but is not re-raised, so it just disappears and the script continues as if there wasn't any error.

Is this the intended behaviour? What is the reason for this if block?

https://github.com/AIIMLab/fexp/blob/f37226a2b0b0b0c269506f7128b138758fffe84b/fexp/writers.py#L56-L64

**Comment by jonasteuwen** [comment]
Hi @gvtulder

Thanks for mentioning. The reason for this was to make the exceptions are bit more pythonic. I will look into this and fix it, this is unintended. I will review your pull request.

**Comment by jonasteuwen** [comment]
Fixed with merge https://github.com/AIIMLab/fexp/pull/1
